Name: nemo-qml-plugin-systemsettings
Summary: System settings plugin for Nemo Mobile
URL: https://github.com/nemomobile/nemo-qml-plugin-systemsettings
Group: System/Libraries
Description: "%{summary}."
Version: 0.0.0
Release: 1
Sources:
    - "%{name}-%{version}.tar.bz2"
License: BSD
Configure: none
Builder: qmake
PkgConfigBR:
    - QtCore >= 4.7.0
    - QtDeclarative
    - qmsystem2
    - profile
    - QtSystemInfo
PkgBR:
    - mce-headers
Files:
    - "%{_libdir}/qt4/imports/org/nemomobile/systemsettings/libnemosystemsettings.so"
    - "%{_libdir}/qt4/imports/org/nemomobile/systemsettings/qmldir"
